version: '3.8'

services:
  db-mazust:
    container_name: PostgreSQL-mazust
    image: postgres
    #restart: on-failure
    expose:
      - 5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: mazust_db
    ports:
      - '5432:5432'
    volumes:

      - ./postgres-data-mazust:/var/lib/postgresql/data